# NCERT PDF URLs discovered using Playwright
# Class: 10
# Language: hi
# Note: Verify these URLs manually before processing

sources:
  - name: "ncert"
    type: "batch"
    kind: "web_pdf"
    urls:
      - "https://ncert.nic.in/textbook/pdf/instruction.pdf"
      - "https://ncert.nic.in/pdf/leading_the_change.pdf"
      - "https://ncert.nic.in/textbook/pdf/bhsr1dd.zip"
    download_dir: "downloads/ncert/class_10"
    language: "hi"
    auto_detect_language: true
    timeout: 30
    max_retries: 3
    metadata:
      source: "NCERT"
      license: "CC-BY-NC"
      category: "textbook"
      class: "10"
      publisher: "National Council of Educational Research and Training"

policies:
  licenses: "src/clean_corpus/policies/defaults/licenses.yaml"
  quality: "src/clean_corpus/policies/defaults/quality.yaml"
  pii: "src/clean_corpus/policies/defaults/pii.yaml"
  curriculum: "src/clean_corpus/policies/defaults/curriculum.yaml"

stages:
  - license_gate
  - sanitize
  - quality_gate
  - pii_policy_gate
  - curriculum_eligibility
